<?php

namespace App;
use App\Article;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug'];

    protected static function boot()
    {
        parent::boot(); //TODO: Change the autogenerated stub

        static::saving(function ($category) {
            $category->slug = str_slug($category->name);
        });

        static::deleting(function ($category) {
            $category->articles->each->delete();
        });
    }

    // public function setNameAttribute($name) {
    //     $this->attributes['name'] = $name;
    //     $this->attributes['slug'] = str_slug($name);
    // }

    public function articles() {
        return $this->hasMany(Article::class);
    }
}
